#define MENU_WIDTH 400
#define MENU_HEIGHT 600
#define MAP_SIZE 30
#define TEXTURE_SIZE 30
#define PLAYER_START_X MAP_SIZE - 3
#define PLAYER_START_Y MAP_SIZE - 3
#define CHEST_X MAP_SIZE - 2
#define CHEST_Y MAP_SIZE - 2
#define LIVES 3
#define BOMBS 3
#define GAME_WIDTH 1000
#define GAME_HEIGHT 900
#define EXIT_WIDTH 300
#define EXIT_HEIGHT 300
#define INDICATOR_SIZE 100